name: setup
runs:
    using: composite
    steps:
        -   name: Setup Node.js environment
            uses: actions/setup-node@v6.1.0
        -   name: Install pnpm
            run: 'npm install pnpm -g'
            shell: bash
        -   name: Restore deps cache
            id: deps-cache-restore
            uses: actions/cache/restore@v5.0.1
            with:
                path: /node_modules
                key: "npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}"
                restore-keys:
                    "npm-dependencies-"
        -   name: Install dependencies
            run: 'pnpm install --frozen-lockfile'
            shell: bash
        -   name: Cache dependencies
            uses: actions/cache/save@v5.0.1
            with:
                path: /node_modules
                key: "npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}"
